"""Initial Schema

Revision ID: 128924e8b574
Revises: 
Create Date: 2026-08-11 00:00:45.635536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128924e8b574'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('IP', 'DOMAIN', 'URL', 'HASH_MD5', 'HASH_SHA256', 'EMAIL', 'CVE', name='ioctype'), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('tlp', sa.Enum('CLEAR', 'GREEN', 'AMBER', 'RED', name='tlplevel'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'WHITELISTED', 'UNDER_REVIEW', name='iocstatus'), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_severity_score'), 'indicators', ['severity_score'], unique=False)
    op.create_index(op.f('ix_indicators_status'), 'indicators', ['status'], unique=False)
    op.create_index(op.f('ix_indicators_type'), 'indicators', ['type'], unique=False)
    op.create_index(op.f('ix_indicators_value'), 'indicators', ['value'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SECURITY_ENGINEER', 'INCIDENT_RESPONDER', 'THREAT_HUNTER', 'SOC_ANALYST', 'EXECUTIVE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('indicator_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_confidence', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_sources')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_indicators_value'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_type'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_status'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_severity_score'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('feeds')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
